### ISSUE TITLE
How do I use image quality ranking?

### ISSUE THREAD

**Issue by GayatriChandran** [sakoho81/miplib#2]
How do I use the image quality assessment functions? For example : In batch_evaluate_image_quality(path, options) what are the '**options**' ?
Also, can I use this method for ranking images of beads?

**Comment by sakoho81** [comment]
Hi Gayatri, 

thanks for asking. I added an [example](https://github.com/sakoho81/miplib/blob/public/Examples/Image_quality_ranking.ipynb) in the Examples directory.

**Comment by GayatriChandran** [comment]
Thanks! I'll try it out
