### ISSUE TITLE
trying to figure out the image input requirements

### ISSUE THREAD

**Issue by aaron4444** [sakoho81/miplib#7]
Hi, 

I liked your article. i was looking for fsc/frc analysis and the work you did to develop deconvolution algorithm based on the psf is pretty neat. I was trying to use it using the library. 

1. if you could update the "FRC based frequency domain filtering" notebooks for broken links? example. ffutils and ideal_fft_filter. didn't take me long to debug but was confusing to figure out where you had moved files. 

2.Could i ask for some ground rules on the shape/format for data that the code is looking for (only square?)   More importantly i'm trying to figure out why i get the following error...only sometimes. I had a stack of 91 images and 90 work but i can't figure out why this one won't. I also tried to upscale an image so 200x200 --> 400x400 and i get the same error. I had a dickens of a time trying to puzzle out how to change args in the arg list. Perhaps there is some size limit? or is it that i'm not correcting some other parameter? i haven't been able to puzzle it out yet. Thank you again. love the code i want to share it with a colleague who might find it useful for x-ray fluorescence microscopy deconvolution. 

![error](https://user-images.githubusercontent.com/20306451/120090658-346a9f00-c0d2-11eb-808e-e84f83b19e21.PNG)

If i could request a meeting to discuss? anm2172@columbia.edu

best regards, 

Aaron

**Comment by aaron4444** [comment]
I think i figured it out. its throwing this when the FRC resolution threshold is too low so when the curve doesn't cross the threshold and thus ends up with an empty array for the cross over for the guess at the the dataset resolution.

**Comment by sakoho81** [comment]
Hi there. That error shows up when the FRC curve for some reason does not go below the specified threshold. Typically because the noise realisations in the two images are not completely independent. Also shows up during deconvolution sometimes. I should add an error message for that.
